"fyll inn profiles-navn fra dbt_project.yml":
  target: "{{env_var('DBT_DB_TARGET')}}"
  outputs:
    U:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: "{{env_var('DBT_DB_DSN', 'dmv07-scan.adeo.no')}}"
      port: 1521
      service: ccdwhu1_ha
      database: dwhu1
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    R:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: "{{env_var('DBT_DB_DSN', 'dm07-scan.adeo.no')}}"
      port: 1521
      service: dwhr
      database: dwhpr
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    Q:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: "{{env_var('DBT_DB_DSN', 'dmv04-scan.adeo.no')}}"
      port: 1521
      service: ccdwhq0_ha
      database: dwhq0
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    P:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: "{{env_var('DBT_DB_DSN', 'dm08-scan.adeo.no')}}"
      port: 1521
      service: dwh_ha
      database: dwhpr
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
