"fyll inn profiles-navn fra dbt_project.yml":
  target: "{{env_var('DBT_DB_TARGET')}}"
  outputs:
    TD:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: "{{env_var('DBT_DB_DSN', '10.51.9.59')}}"
      port: 1521
      service: dwh_td
      database: DWH_TD
      schema: "{{env_var('DBT_USER')}}"
      threads: 4
    U:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv04-scan.adeo.no
      port: 1521
      dbname: dwhu1
      service: ccfdwhu1
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 4
    R:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv04-scan.adeo.no
      port: 1521
      dbname: dwhpr
      service: dwhr_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 4
    Q:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: "{{env_var('DBT_DB_DSN', 'dmv04-scan.adeo.no')}}"
      port: 1521
      service: ccdwhq0_ha
      database: dwhq0
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 4
    P:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv09-scan.adeo.no
      port: 1521
      dbname: dwhpr
      service: dwh_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 4
